services:
  # Сервис для фронтенда (только сборка)
  frontend:
    image: ghcr.io/viktoriashev/frontend:latest
    container_name: frontend
    volumes:
      - frontend:/app/dist # Файлы сохраняем в volume
    networks:
      - frontend_network
    depends_on:
      - backend
    env_file:
      - .env

  # Сервис для бэкенда
  backend:
    image: ghcr.io/viktoriashev/backend:latest
    container_name: backend
    env_file:
      - .env
    networks:
      - backend_network
      - internet_internal
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  # Сервис для базы данных PostgreSQL
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./backend/test/prac.init.sql:/docker-entrypoint-initdb.d/1_init.sql:ro
      - ./backend/test/prac.films.sql:/docker-entrypoint-initdb.d/2_films.sql:ro
      - ./backend/test/prac.schedules.sql:/docker-entrypoint-initdb.d/3_schedules.sql:ro
    networks:
      - internet_internal
    restart: unless-stopped

  # Сервис для pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    env_file:
      - ./.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - internet_internal
      - backend_network
    depends_on:
      - postgres
    restart: unless-stopped

  # Сервис для Nginx (исправленный отступ)
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend:/var/www/frontend:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro # Монтирование сертификатов
    networks:
      - frontend_network
      - backend_network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  frontend:
  postgres:
  pgadmin:

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
  internet_internal:
    driver: bridge
    internal: true
